### ISSUE TITLE
Set the minimum and maximum color bar

### ISSUE THREAD

**Issue by hamdaniari** [timofeymukha/turbulucid#8]
Hi there,

Firstly, I would like to appreciate your work on the turbulucid.
It is very useful for the unstructured grid.

I need to use one color bar for many figures in one plot. 
Anyway, how do we set the minimum and maximum color bar?
It is usually set by defining vmin and vmax.

**Comment by timofeymukha** [comment]
Hi @hamdaniari 

I usually do something like this
```
p = tbl.plot_field(case.case, 'alpha.waterMean', xlim=[-1, 6.5], ylim=[0, 2.5],
                           colorbar=False)
p.set_clim([0, 1.0])
c = tbl.add_colorbar(p, aspect=10, ticks=[0, 0.25, 0.5, 0.75, 1.0])
```
Here, `tbl` is `turbulucid`. The `colorbar=False` will stop `plot_field` from initially adding a colorbar.
Then it is explicitly added using the `tbl.addcolorbar` function.
I use `clim` to adjust the value range in the plot, and then the colorbar is automatically set to that range.

**Comment by hamdaniari** [comment]
Hi @timofeymukha 

Thank you so much for your quick response.

I successfully adjust the value by `clim` 
Now I am writing an international journal paper and I am using turbulucid.
I will make sure to cite your paper.

Once again, thank you @timofeymukha

**Comment by timofeymukha** [comment]
@hamdaniari Great, glad I could help out!
